/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appsupportjobs;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import model.Jobs;
import model.JobsDAO;

/**
 *
 * @author Admin
 */
public class CRUDJobs extends javax.swing.JFrame {
    String id_Jobs;
    JobsDAO dao = new JobsDAO();
    
    public CRUDJobs() {
        initComponents();
        fillTable();
    }
    public void fillTable(){
        DefaultTableModel tbModel = (DefaultTableModel) tbJobs.getModel();
        tbModel.setRowCount(0);
        for(Jobs jd : dao.getAllJobs()){
            Object dataRow[] = new Object[12];
            dataRow[0] = jd.getJobs_id();
            dataRow[1] = jd.getLocation_id();
            dataRow[2] = jd.getJobs_title();
            dataRow[3] = jd.getJobs_status();
            dataRow[4] = jd.getPost_date();
            dataRow[5] = jd.getCompany();
            dataRow[6] = jd.getJobs_location();
            dataRow[7] = jd.getJobs_description();
            dataRow[8] = jd.getJobs_mail();
            dataRow[9] = jd.getSalary();
            dataRow[10] = jd.getJobs_type();
            dataRow[11] = jd.getJobs_skill();
            tbModel.addRow(dataRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbJobs = new javax.swing.JTable();
        txtJobsID = new javax.swing.JTextField();
        txtLocationID = new javax.swing.JTextField();
        txtJobsTitle = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtPostDate = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtJobsLocation = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtJobsType = new javax.swing.JTextField();
        txtJobsSkill = new javax.swing.JTextField();
        btnAddJobs = new javax.swing.JButton();
        btnDeleteJobs = new javax.swing.JButton();
        btnEditJobs = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtJobsRes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextJobsDes = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Jobs Manager");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Jobs ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Location ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jobs Title");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jobs Status");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Post Date");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Company");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Jobs Location");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Jobs Description");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Salary");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Jobs Type");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Jobs Skill");

        tbJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Jobs ID", "LocationID", "Jobs Title ", "Jobs Status", "Post Date", "Company", "Jobs Location", "Jobs Description", "Jobs Mail", "Salary", "Jobs Type", "Jobs Skill"
            }
        ));
        tbJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJobsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbJobs);

        txtJobsID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLocationID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtJobsTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPostDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCompany.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtJobsLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtJobsType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtJobsSkill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAddJobs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddJobs.setText("Add Jobs");
        btnAddJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJobsActionPerformed(evt);
            }
        });

        btnDeleteJobs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteJobs.setText("Delete Jobs");
        btnDeleteJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteJobsActionPerformed(evt);
            }
        });

        btnEditJobs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditJobs.setText("Update Jobs");
        btnEditJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditJobsActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Jobs Mail");

        txtJobsRes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TextJobsDes.setColumns(20);
        TextJobsDes.setRows(5);
        jScrollPane2.setViewportView(TextJobsDes);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(472, 472, 472))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtJobsID)
                                                .addComponent(txtLocationID, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                            .addComponent(txtJobsTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtJobsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtStatus)
                                                .addComponent(txtPostDate)
                                                .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                    .addComponent(txtJobsType)
                                                    .addComponent(txtJobsSkill)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtJobsRes, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEditJobs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(btnAddJobs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteJobs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtJobsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtLocationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtJobsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtJobsRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPostDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtJobsType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtJobsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtJobsSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validateForm(){
        if(txtJobsID.getText().isEmpty() || txtLocationID.getText().isEmpty() || txtJobsTitle.getText().isEmpty() || txtStatus.getText().isEmpty() || txtPostDate.getText().isEmpty() || txtCompany.getText().isEmpty() || txtJobsLocation.getText().isEmpty() || TextJobsDes.getText().isEmpty() || txtJobsRes.getText().isEmpty() || txtSalary.getText().isEmpty() || txtJobsType.getText().isEmpty() || txtJobsSkill.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    public Jobs getModel(){
        Jobs jd = new Jobs();
        jd.setJobs_id(txtJobsID.getText());
        jd.setLocation_id(txtLocationID.getText());
        jd.setJobs_title(txtJobsTitle.getText());
        jd.setJobs_status(txtStatus.getText());
        jd.setPost_date(txtPostDate.getText());
        jd.setCompany(txtCompany.getText());
        jd.setJobs_location(txtJobsLocation.getText());
        jd.setJobs_description(TextJobsDes.getText());
        jd.setJobs_mail(txtJobsRes.getText());
        jd.setSalary(txtSalary.getText());
        jd.setJobs_type(txtJobsType.getText());
        jd.setJobs_skill(txtJobsSkill.getText());
        return jd;
    }
    
    private void btnAddJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobsActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            Jobs jd = getModel();
            try {
                if(dao.addJobs(jd) > 0){
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    fillTable();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Loi: " + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin");
        }
    }//GEN-LAST:event_btnAddJobsActionPerformed

    public void setModel(Jobs jd){
        txtJobsID.setText(jd.getJobs_id());
        txtLocationID.setText(jd.getLocation_id());
        txtJobsTitle.setText(jd.getJobs_title());
        txtStatus.setText(jd.getJobs_status());
        txtPostDate.setText(jd.getPost_date());
        txtCompany.setText(jd.getCompany());
        txtJobsLocation.setText(jd.getJobs_location());
        TextJobsDes.setText(jd.getJobs_description());
        txtJobsRes.setText(jd.getJobs_mail());
        txtSalary.setText(jd.getSalary());
        txtJobsType.setText(jd.getJobs_type());
        txtJobsSkill.setText(jd.getJobs_skill());
    }
    
    private void tbJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJobsMouseClicked
        // TODO add your handling code here:
        int id  = tbJobs.rowAtPoint(evt.getPoint());
        id_Jobs = tbJobs.getValueAt(id, 0).toString();
        Jobs jd = dao.getJobsByID(id_Jobs);
        setModel(jd);
    }//GEN-LAST:event_tbJobsMouseClicked

    private void btnEditJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditJobsActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            try {
                Jobs jds = getModel();
                if(dao.updateJobs(jds) > 0){
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    fillTable();
                } 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Loi: " + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chua nhập thông tin");
        }
    }//GEN-LAST:event_btnEditJobsActionPerformed

    private void btnDeleteJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteJobsActionPerformed
        // TODO add your handling code here:
        if (txtJobsID.getText().isEmpty() || id_Jobs.length() == 0){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin");
        } else {
            try {
                if(id_Jobs.length() > 0){
                    dao.deleteJobs(id_Jobs);
                } else {
                    dao.deleteJobs(txtJobsID.getText());
                }
                fillTable();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnDeleteJobsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManagerFrom mgF = new ManagerFrom();
        mgF.setLocationRelativeTo(null);
        mgF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDJobs jobs = new CRUDJobs();
                jobs.setLocationRelativeTo(null);
                jobs.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextJobsDes;
    private javax.swing.JButton btnAddJobs;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteJobs;
    private javax.swing.JButton btnEditJobs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbJobs;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtJobsID;
    private javax.swing.JTextField txtJobsLocation;
    private javax.swing.JTextField txtJobsRes;
    private javax.swing.JTextField txtJobsSkill;
    private javax.swing.JTextField txtJobsTitle;
    private javax.swing.JTextField txtJobsType;
    private javax.swing.JTextField txtLocationID;
    private javax.swing.JTextField txtPostDate;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
